name: Deploy to gh-pages branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build site (copy files)
        run: |
          rm -rf dist
          mkdir -p dist
          cp assets/webpages/assignment1.html dist/
          cp assets/webpages/assignment2.html dist/
          cp assets/webpages/login.html dist/
          cat > dist/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=login.html">
          <link rel="canonical" href="login.html">
          HTML

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          force_orphan: true
